### ISSUE TITLE
Investigate pinterest board names issue

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/tweet-old-post#282]
my name dashboard <--- doesn't work
my_name_dashboard <--- works
my-name-dashboard <--- works

**Comment by UVLabs** [comment]
Tested and works, already fixed this in https://github.com/Codeinwp/tweet-old-post/commit/c7ddf9f742dcc59b840c39d262d3c74d486fc1be#diff-ae89571439a7e12b1c54632ca9415521

**Comment by selul** [comment]
@UVLabs just an idea, you can reference the issue into the commit message with #<issue no> instead of pasting here the commit link. 

So if you have added this commit message `fixed not posting an issue for boards with a space in the name ref #282` the commit will be linked appear in this issue thread.

**Comment by UVLabs** [comment]
@selul yeah Im aware, the thing is this was fixed months ago but a user reported it recently and I tested on my install to find out it works so I added the link to the commit where I had fixed it a long time ago, I'll investigate again if this comes up but i think it was an issue on the user end
