### ISSUE TITLE
Rviv.ly not always returning link

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/tweet-old-post#331]
Facebook returns `invalid parameter` 

Linkedin returns error requiring `submitted link`

Twitter doesn't include the link 

etc

**Comment by UVLabs** [comment]
Issue seems to be with rvivly creating new links

**Comment by mariusvetrici** [comment]
@UVLabs pls provide here:
- the repro steps (bullet list of things that need to be performed to get the bug)
- the expected, correct result that we need to achieve.

**Comment by UVLabs** [comment]
To test: 

- Create a new blank site
- Create new dummy post
- Turn on shortener with rviv.ly option checked
![image](https://user-images.githubusercontent.com/10324144/62556864-cb9e9c80-b843-11e9-811b-12fa0ff1f672.png)

- Start sharing. 

Because of these lines: https://github.com/Codeinwp/tweet-old-post/blob/master/includes/admin/shortners/class-rop-rvivly-shortner.php#L77-L79 if the shortening does not work then it will return the original URL, when actually it should be returning the **shortened URL.**

**Comment by mariusvetrici** [comment]
I believe the rviv.ly server is the culprit here, there's nothing to be fixed in the plugin itself.

None of my posts could get a valid URL from rviv.ly, the response is always code 200 with an empty body instead of the short URL. Performing the request via Postman yields the same result ([Screen](https://imgur.com/Jf9h6nf)). Omitting the signature parameter returns the correct response for that scenario  ([Screen](https://imgur.com/JxqY0XJ)), so the server seems to be functional, just not processing URLs properly.

I also tried using "signature" and "website" values containing our "http://rop.ernomo.re" staging to make sure the problem wasn't that rviv.ly could not reach my local env. Still an empty response.

Alex N.

**Comment by selul** [comment]
Indeed, you were right. I did check the rviv.ly server and it had an issue, not it should be working fine.

**Comment by mariusvetrici** [comment]
Looks good!
Twitter: https://d.pr/i/t1Xize 
Linkedin: https://d.pr/i/GI34wK 

The issue will be moved directly to Done since it was investigated and discussed with the team.
