### ISSUE TITLE
advanced schedule redesign

### ISSUE THREAD

**Issue by selu91** [Codeinwp/tweet-old-post#51]
@claudiuvertistudio i would like to help me with some design changes: 

1. http://prntscr.com/awk24h -  it shows up when you go to the Advanced Schedule tab and the plugin is not started

2. http://prntscr.com/awk2ke - it shows up when you dont have any posts to share. To replicate this, check all categories from the general tab.

3. http://prntscr.com/awk3b0 - the advance schedule tab when the plugin is started. i would like to have a timeline like design, with a header with the date and each posts, maybe smth like this: https://player.vimeo.com/video/151662368 . 

4. Also you need to study the behaviour when we have just one network and and when we have two. When we have two, a new sidebar comes in. 

5. Also for edit and delete i would like to have icons instead of text.

7.  For each post to have the network icon too. You have a class for each post which you can use to target the network: http://prntscr.com/awkszx . 

6. I would like to remove this badge for advanced schedule: http://prntscr.com/awkgrs and a small light banner between between tabs and timeline with **Editing features are available on the Business version**

4. For this you need to have the pro addon: http://prntscr.com/awkiug . After you have it, you can click on edit and see this form. We need to stile this a bit. 

5. http://prntscr.com/awkj8b - it shows up when we click to delete. We need to style this a bit too.

For all the changes, dont change the markup, classes or ids. Just add new classes or ids if you want, but dont remove or change the already defined ones.

**Comment by ineagu** [comment]
@claudiuvertistudio I would remove the pro version badge, since this it can be used in the free version as well ( limited ) and having the 2 pro version there makes that we are trying too much to sell

Now when you try to edit/delete you are just scrolled at the top, I would show a popup saying that you cannot edit/delete queue if you don't have the business package.

I would rename Advanced Scheduling to : Manage queue, ce parere ai @selu91  ?
