### ISSUE TITLE
Escape slashes appearing in content

### ISSUE THREAD

**Issue by topher1kenobe** [Codeinwp/tweet-old-post#781]
In Twitter, as well as others, escape slashes are being sent to the content.

<img width="626" alt="Screen Shot 2021-03-16 at 5 56 50 PM" src="https://user-images.githubusercontent.com/341412/111487106-7492c600-870e-11eb-96e1-91294d676230.png">

**Comment by UVLabs** [comment]
This will be fixed in the next version of ROP, for now you can fix it by adding the following code to site specific plugin or your functions.php file:

```
function rop_filter_instant_sharing($message, $event){
	$message = wp_kses_stripslashes( $message );
	return $message;
}
add_filter('rop_instant_share_message', 'rop_filter_instant_sharing', 10, 2)
```

Alternatively, you can do the change that was done here: https://github.com/Codeinwp/tweet-old-post/pull/783/commits/f4e5c2ae5ffb6113fbf8f83b43f6dcdcb81f27c4#diff-fcd6c0c59094f9f01bad1a79875057bfc1becc743535d2cdb5c90f7e2bedd202R1023

**Comment by ckeeney** [comment]
I'm running `v9.0.1` and I'm still seeing escaped apostophes.

The mentioned fix only fixes the escaped apostophes for posts made through the cron.

If "True Instant Share" is enabled, the above fix is never applied.

**Comment by UVLabs** [comment]
@ckeeney thanks, change this line here: https://github.com/Codeinwp/tweet-old-post/blob/master/includes/admin/class-rop-admin.php#L1029 to instead be:

`$message = apply_filters( 'rop_instant_share_message', stripslashes( $message ), $event );`

This will be fixed in the next version

**Comment by ckeeney** [comment]
Thanks.  Sorry I'd open a PR but I'm out of town right now.  I can do it next week if this still needs done.

**Comment by UVLabs** [comment]
@ckeeney I've already pushed the change to dev branch, the fix will be out in a few weeks so thats fine, thank you for reporting
