### ISSUE TITLE
Redirection error due to array value

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/tweet-old-post#916]
### Description

Several users complained about the fact that they have not been redirected when trying to connect to Facebook since the latest update.

error encountered: Value is empty : pages in Array ( [id] => czoxNjoiMjI0NTI3NjA2MjMyOTk3MSI7 [pages] => Array ( ) )

ref: https://secure.helpscout.net/conversation/2512440165/404898?viewId=212385

### Step-by-step reproduction instructions

1. Go to the ROP dashboard
2. Click to add a new Facebook account
3. Make the configurations

### Screenshots, screen recording, code snippet or Help Scout ticket

<img width="1680" alt="image" src="https://github.com/Codeinwp/tweet-old-post/assets/86592992/81fefe21-64f2-482d-9faf-5bdcedbd20a5">
<img width="1526" alt="image" src="https://github.com/Codeinwp/tweet-old-post/assets/86592992/7fb32f56-d302-45ea-9acd-11b03a19f497">
I know the above error appears when you're not admin, as per - https://docs.revive.social/article/1374-facebook-error-value-is-empty-pages-in-array, but I am an admin, and I still get this error.

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by AndreeaCristinaRadacina** [comment]
+1 https://secure.helpscout.net/conversation/2501854913/403271?viewId=212385

**Comment by AndreeaCristinaRadacina** [comment]
+1 https://secure.helpscout.net/conversation/2512434982/404896?viewId=212385

**Comment by AndreeaCristinaRadacina** [comment]
+1 https://secure.helpscout.net/conversation/2511472493/404782?viewId=212385

**Comment by AndreeaCristinaRadacina** [comment]
+1 https://wordpress.org/support/topic/facebook-authorisation-not-redirecting/

**Comment by poonam279** [comment]
+1 https://secure.helpscout.net/conversation/2502169911/403319/

**Comment by AndreeaCristinaRadacina** [comment]
+1 https://secure.helpscout.net/conversation/2513519348/405023?viewId=212385

**Comment by Soare-Robert-Daniel** [comment]
Regarding the functionality. The login and sharing posts with Facebook are working.

What needs to be fixed is the redirect after authorization.

After we authorize the user in the popup, we inform them that a redirect must be done, and if it is not done, we tell them to inform the support. 

---

The problem is that controlling the popup with a different origin is unstable. 

When trying to programmatically close the popup, a dom exception is raised. See https://developer.mozilla.org/en-US/docs/Web/API/Window/open#same-origin_policy

<img width="1187" alt="Screenshot 2024-02-19 at 14 42 22" src="https://github.com/Codeinwp/tweet-old-post/assets/17597852/7110a5e2-cc80-4855-9443-dd8cd8465e4b">

Because of this error, the next step, which is the page reload, is not done. Thus, the user does not observe that the account might have already been added. 

--- 

### Changing the flow

Once the authorization is in the popup. We do two things:
- Reload the plugin dashboard page; thus, the user will see the refreshed page.
- In the popup, tell the user that the account info has been sent and that he can close the popup if he sees the account added. (We remove all mentions of redirect since we are no longer doing it.) -- If the user does not see the account, he can take a screenshot and send it to support.

@vytisbulkevicius

**Comment by AndreeaCristinaRadacina** [comment]
+1 https://secure.helpscout.net/conversation/2511034371/404706?viewId=931544

**Comment by poonam279** [comment]
+1 https://secure.helpscout.net/conversation/2515357973/405248?folderId=212385

**Comment by AndreeaCristinaRadacina** [comment]
+1 https://secure.helpscout.net/conversation/2513631661/405035?viewId=212385

**Comment by Soare-Robert-Daniel** [comment]
> +1 https://secure.helpscout.net/conversation/2515357973/405248?folderId=212385

This is related to the refresh. https://github.com/Codeinwp/tweet-old-post/pull/918

> https://secure.helpscout.net/conversation/2513631661/405035?viewId=212385
> https://secure.helpscout.net/conversation/2515310322/405245?viewId=212385

Those two need to reintroduce their X, Twitter account since we changed the server, and they used our App to post.

For Facebook, I think it is the same. They need to reintroduce their account to allow for new permissions.

**Comment by AndreeaCristinaRadacina** [comment]
+1 https://secure.helpscout.net/conversation/2513577549/405031?viewId=931544

**Comment by AndreeaCristinaRadacina** [comment]
@Soare-Robert-Daniel another customer reported this issue - https://secure.helpscout.net/conversation/2512168501/404876?viewId=212385

He has multiple Facebook accounts and some of them cannot be connected. He gets an error similar to what is described in this issue. Can you kindly confirm if it's the same or if I should open another issue?
![file](https://github.com/Codeinwp/tweet-old-post/assets/86592992/befaf0f0-5c1a-4686-84fb-7da0a22c7055)

**Comment by AndreeaCristinaRadacina** [comment]
+1 https://secure.helpscout.net/conversation/2530924960/407433?viewId=212385

**Comment by AndreeaCristinaRadacina** [comment]
Everything is fine now. The Business pages are also added.
